import { Request, Response } from 'express';
import { AuthRequest } from '../middleware/auth';
import { queryDb } from '../database';
import { processLLMRequest } from '../services/llm.service';
import fs from 'fs';
import path from 'path';
import { exec, spawn } from 'child_process';

const SANDBOX_ROOT = path.resolve('d:/Projects/minimalism-ai/sandbox_workspace');
let activeChildProcess: any = null;

// Ensure Sandbox Directory exists and is scaffolded
function ensureSandboxScaffolded() {
  if (!fs.existsSync(SANDBOX_ROOT)) {
    fs.mkdirSync(SANDBOX_ROOT, { recursive: true });
  }

  // Scaffold default files if empty
  const files = fs.readdirSync(SANDBOX_ROOT);
  if (files.length === 0) {
    // 1. package.json
    fs.writeFileSync(
      path.join(SANDBOX_ROOT, 'package.json'),
      JSON.stringify(
        {
          name: 'minimalism-sandbox-app',
          version: '1.0.0',
          description: 'Autonomous Generative Sandbox Platform',
          main: 'src/main.js',
          scripts: {
            start: 'node src/main.js',
            test: 'echo "Error: no test specified" && exit 0'
          },
          dependencies: {}
        },
        null,
        2
      )
    );

    // 2. src folder
    const srcDir = path.join(SANDBOX_ROOT, 'src');
    fs.mkdirSync(srcDir, { recursive: true });

    // 3. src/index.html
    fs.writeFileSync(
      path.join(srcDir, 'index.html'),
      `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Minimalism AI Sandbox App</title>
  <style>
    body {
      background-color: #000000;
      color: #ffffff;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      margin: 0;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      overflow: hidden;
    }
    .container {
      text-align: center;
      border: 1px solid #333333;
      padding: 40px;
      border-radius: 8px;
      max-width: 480px;
      background-color: #0a0a0a;
    }
    h1 {
      font-size: 24px;
      font-weight: 300;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      margin-bottom: 20px;
    }
    p {
      font-size: 14px;
      color: #888888;
      line-height: 1.6;
      margin-bottom: 30px;
    }
    .btn {
      background-color: #ffffff;
      color: #000000;
      border: none;
      padding: 10px 24px;
      font-size: 12px;
      text-transform: uppercase;
      font-weight: bold;
      letter-spacing: 0.05em;
      border-radius: 4px;
      cursor: pointer;
      transition: all 0.3s ease;
    }
    .btn:hover {
      background-color: #cccccc;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Autonomous Workspace</h1>
    <p>This is a real web application dynamically compiled and built on your disk. You can use the prompt terminal to generate pages, adjust styles, or install features dynamically.</p>
    <button class="btn" id="actionBtn">INTERACT</button>
  </div>

  <script src="main.js"></script>
</body>
</html>`
    );

    // 4. src/main.js
    fs.writeFileSync(
      path.join(srcDir, 'main.js'),
      `// Interactive script for the Sandbox Web app
document.getElementById('actionBtn').addEventListener('click', () => {
  const h1 = document.querySelector('h1');
  h1.textContent = 'SYSTEM ACTIVE';
  h1.style.color = '#ffffff';
  console.log('Action button clicked inside sandboxed application.');
  alert('Autonomous interaction verified successfully!');
});`
    );

    // 5. README.md
    fs.writeFileSync(
      path.join(SANDBOX_ROOT, 'README.md'),
      `# Minimalism AI - Autonomous Generative Sandbox

This folder houses the live project generated by the **Minimalism AI Autonomous Coding Agent**.
Every file here is real, editable, and dynamically orchestrated.

### Commands
- \`npm start\`: Starts the application logic.
- \`npm test\`: Runs sandbox unit checks.
`
    );
  }
}

// Clear all generated files from the sandbox (keeps directory structure, wipes src/ and generated files)
function clearSandboxWorkspace() {
  const clearDir = (dir: string) => {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const fullPath = path.join(dir, entry.name);
      // Never delete node_modules or .git
      if (entry.name === 'node_modules' || entry.name === '.git') continue;
      if (entry.isDirectory()) {
        clearDir(fullPath);
        try { fs.rmdirSync(fullPath); } catch (e) {} // remove if empty
      } else {
        // Keep package.json and README.md
        if (entry.name === 'package.json' || entry.name === 'README.md') continue;
        fs.unlinkSync(fullPath);
      }
    }
  };
  clearDir(SANDBOX_ROOT);
  // Re-scaffold the src directory so the server still has a valid structure
  const srcDir = path.join(SANDBOX_ROOT, 'src');
  if (!fs.existsSync(srcDir)) {
    fs.mkdirSync(srcDir, { recursive: true });
  }
}


// Safely verify and resolve file paths inside sandbox to avoid directory traversal
function safeResolvePath(relativePath: string): string {
  const resolved = path.resolve(SANDBOX_ROOT, relativePath);
  if (!resolved.startsWith(SANDBOX_ROOT)) {
    throw new Error('Access Denied: Path escapes sandbox boundary.');
  }
  return resolved;
}

// Recursively fetch files inside the sandbox
interface WorkspaceFile {
  path: string;
  name: string;
  type: 'file' | 'directory';
  content?: string;
  children?: WorkspaceFile[];
}

function scanDirectory(dir: string, relativeRoot = ''): WorkspaceFile[] {
  const items = fs.readdirSync(dir, { withFileTypes: true });
  const results: WorkspaceFile[] = [];

  for (const item of items) {
    const relativePath = path.join(relativeRoot, item.name).replace(/\\/g, '/');
    const absolutePath = path.join(dir, item.name);

    if (item.isDirectory()) {
      // Exclude node_modules, .git, dist for performance
      if (item.name === 'node_modules' || item.name === '.git' || item.name === 'dist') {
        continue;
      }
      results.push({
        path: relativePath,
        name: item.name,
        type: 'directory',
        children: scanDirectory(absolutePath, relativePath)
      });
    } else {
      // Only read files that are common text types to prevent binary pollution
      const ext = path.extname(item.name).toLowerCase();
      const textExtensions = ['.html', '.css', '.js', '.ts', '.json', '.md', '.txt', '.prisma', '.env'];
      let content = '';
      if (textExtensions.includes(ext)) {
        try {
          content = fs.readFileSync(absolutePath, 'utf-8');
        } catch (e) {
          content = '[Failed to read file contents]';
        }
      } else {
        content = '[Binary file binary data not loaded]';
      }

      results.push({
        path: relativePath,
        name: item.name,
        type: 'file',
        content
      });
    }
  }

  // Sort directories first, then files alphabetically
  return results.sort((a, b) => {
    if (a.type !== b.type) {
      return a.type === 'directory' ? -1 : 1;
    }
    return a.name.localeCompare(b.name);
  });
}

// --- CONTROLLER ACTIONS ---

// 1. GET /api/workspace/files
export const getWorkspaceFiles = async (req: AuthRequest, res: Response) => {
  try {
    ensureSandboxScaffolded();
    const files = scanDirectory(SANDBOX_ROOT);
    return res.json({ files });
  } catch (error: any) {
    console.error('Get Workspace Files Error:', error);
    return res.status(500).json({ error: error.message || 'Failed to list workspace files.' });
  }
};

// 1b. POST /api/workspace/clear (wipe sandbox for fresh project)
export const clearWorkspace = async (req: AuthRequest, res: Response) => {
  try {
    clearSandboxWorkspace();
    return res.json({ success: true, message: 'Sandbox workspace cleared successfully.' });
  } catch (error: any) {
    console.error('Clear Workspace Error:', error);
    return res.status(500).json({ error: error.message || 'Failed to clear workspace.' });
  }
};


// 2. POST /api/workspace/write
export const writeWorkspaceFile = async (req: AuthRequest, res: Response) => {
  try {
    const { filePath, content } = req.body;
    if (!filePath) {
      return res.status(400).json({ error: 'File path is required.' });
    }

    const resolved = safeResolvePath(filePath);
    const parentDir = path.dirname(resolved);

    // Create directories if they do not exist
    if (!fs.existsSync(parentDir)) {
      fs.mkdirSync(parentDir, { recursive: true });
    }

    fs.writeFileSync(resolved, content || '');
    return res.json({ success: true, path: filePath });
  } catch (error: any) {
    console.error('Write File Error:', error);
    return res.status(500).json({ error: error.message || 'Failed to write file.' });
  }
};

// 3. POST /api/workspace/delete
export const deleteWorkspaceFile = async (req: AuthRequest, res: Response) => {
  try {
    const { filePath } = req.body;
    if (!filePath) {
      return res.status(400).json({ error: 'File path is required.' });
    }

    const resolved = safeResolvePath(filePath);
    if (!fs.existsSync(resolved)) {
      return res.status(404).json({ error: 'File or directory not found.' });
    }

    const stat = fs.statSync(resolved);
    if (stat.isDirectory()) {
      fs.rmSync(resolved, { recursive: true, force: true });
    } else {
      fs.unlinkSync(resolved);
    }

    return res.json({ success: true, path: filePath });
  } catch (error: any) {
    console.error('Delete File Error:', error);
    return res.status(500).json({ error: error.message || 'Failed to delete path.' });
  }
};

// 4. POST /api/workspace/execute
export const executeWorkspaceCommand = async (req: AuthRequest, res: Response) => {
  try {
    const { command } = req.body;
    if (!command) {
      return res.status(400).json({ error: 'Command is required.' });
    }

    // Restrict executing dangerous destructive commands
    const lower = command.toLowerCase().trim();
    if (lower.includes('rm -rf') || lower.includes('format') || lower.includes('mkfs') || lower.includes('shutdown')) {
      return res.status(400).json({ error: 'Command blocked: Unsafe shell execution.' });
    }

    exec(command, { cwd: SANDBOX_ROOT, timeout: 15000 }, (error, stdout, stderr) => {
      return res.json({
        success: !error,
        stdout: stdout || '',
        stderr: stderr || '',
        exitCode: error ? error.code : 0
      });
    });
  } catch (error: any) {
    console.error('Execute Command Error:', error);
    return res.status(500).json({ error: error.message || 'Failed to run command.' });
  }
};

// 4.1. GET /api/workspace/stream-execute (SSE Real shell stream compiler)
export const streamWorkspaceExecute = async (req: AuthRequest, res: Response) => {
  try {
    const command = req.query.command as string;
    if (!command) {
      return res.status(400).json({ error: 'Command is required.' });
    }

    // Restrict executing dangerous destructive commands
    const lower = command.toLowerCase().trim();
    if (lower.includes('rm -rf') || lower.includes('format') || lower.includes('mkfs') || lower.includes('shutdown')) {
      return res.status(400).json({ error: 'Command blocked: Unsafe shell execution.' });
    }

    // Set SSE headers
    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive',
      'Access-Control-Allow-Origin': '*'
    });

    // Send initial status message
    res.write(`data: ${JSON.stringify({ type: 'stdout', text: `[SYSTEM] Spawning process: ${command}\n` })}\n\n`);

    // Kill existing active child process if running to prevent port lockups
    if (activeChildProcess) {
      try {
        res.write(`data: ${JSON.stringify({ type: 'stdout', text: `[SYSTEM] Terminating active running process to prevent collision...\n` })}\n\n`);
        activeChildProcess.kill('SIGINT');
      } catch (e) {}
    }

    // Spawn the shell process natively inside the sandboxed workspace folder
    activeChildProcess = spawn(command, { shell: true, cwd: SANDBOX_ROOT });

    activeChildProcess.stdout.on('data', (chunk: any) => {
      res.write(`data: ${JSON.stringify({ type: 'stdout', text: chunk.toString() })}\n\n`);
    });

    activeChildProcess.stderr.on('data', (chunk: any) => {
      res.write(`data: ${JSON.stringify({ type: 'stderr', text: chunk.toString() })}\n\n`);
    });

    activeChildProcess.on('error', (err: any) => {
      res.write(`data: ${JSON.stringify({ type: 'error', text: err.message })}\n\n`);
      res.end();
      activeChildProcess = null;
    });

    activeChildProcess.on('close', (code: number) => {
      res.write(`data: ${JSON.stringify({ type: 'exit', code })}\n\n`);
      res.end();
      activeChildProcess = null;
    });

  } catch (error: any) {
    console.error('SSE Spawn Error:', error);
    try {
      res.write(`data: ${JSON.stringify({ type: 'error', text: error.message || 'Stream initiation failed.' })}\n\n`);
      res.end();
    } catch (e) {}
  }
};

// Flatten recursive file structure for LLM context injection
function flattenFilesForContext(files: WorkspaceFile[]): string {
  let context = '';
  function traverse(item: WorkspaceFile) {
    if (item.type === 'file') {
      context += `\n[FILE: ${item.path}]\n${item.content || ''}\n[END_FILE]\n`;
    } else if (item.children) {
      for (const child of item.children) {
        traverse(child);
      }
    }
  }

  for (const item of files) {
    traverse(item);
  }
  return context;
}

// 5. POST /api/workspace/generate (CORE PROMPT-TO-CODE ENGINE)
export const generateWorkspaceCode = async (req: AuthRequest, res: Response) => {
  try {
    const { prompt, model } = req.body;
    const user = req.user;

    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required.' });
    }

    ensureSandboxScaffolded();

    // 1a. Clear sandbox before generating so each new project starts fresh
    clearSandboxWorkspace();
    ensureSandboxScaffolded(); // re-scaffold after clear

    // 1. Deduct developer credits (generation costs 3 credits for full pipeline reasoning)
    const ledger = await queryDb.getLedger(user.id);
    const available = ledger ? (15 - ledger.daily_prompts_used) : 0;
    const creditCost = 3;

    if (available < creditCost) {
      return res.status(403).json({
        error: 'Insufficient credits. Please upgrade your plan to access the Autonomous Code Generation Engine.',
        creditsRemaining: available
      });
    }

    // 2. Fetch full real context of all active workspace files
    const workspaceFiles = scanDirectory(SANDBOX_ROOT);
    const filesContext = flattenFilesForContext(workspaceFiles);

    // 3. Inject strict structural directives to LLM
    const developerSystemPrompt = `
You are the Minimalism Code Engine — the world's most precise autonomous UI compilation system.
Your single job: convert a natural language description into a PIXEL-PERFECT, FULLY-FUNCTIONAL, VISUALLY STUNNING single-page web application that impresses on first load.

═══════════════════════════════════════════════
STEP 1 — THINK FIRST (Chain-of-Thought Planning)
═══════════════════════════════════════════════
Before writing any code, silently reason through:
- What is the user actually trying to build? What's the core use case?
- What sections/components does this page need?
- What color palette best fits this product? (dark? light? corporate? playful?)
- What interactions / micro-animations would make it feel alive?
- How should the layout work on mobile vs desktop?
Then write your 2-3 line architectural summary, then jump straight to the file blocks.

═══════════════════════════════════════════════════
STEP 2 — CODE QUALITY MANDATES (ALL ARE REQUIRED)
═══════════════════════════════════════════════════

[TYPOGRAPHY]
- ALWAYS import from Google Fonts CDN: Inter, Outfit, Plus Jakarta Sans, or Sora
- Use a clear type scale: display (48-64px), h1 (32-40px), h2 (24-28px), body (14-16px), caption (11-12px)
- letter-spacing: 0.02em for body, -0.03em for large headings

[COLORS]
- Define all colors as CSS custom properties at :root level
- Dark theme template:
  :root {
    --bg-primary: #09090b;
    --bg-secondary: #111114;
    --bg-card: #18181b;
    --border: rgba(255,255,255,0.08);
    --text-primary: #fafafa;
    --text-secondary: #a1a1aa;
    --text-muted: #52525b;
    --accent: #e4e4e7;
    --accent-hover: #ffffff;
  }
- Light theme template:
  :root {
    --bg-primary: #f8f8f9;
    --bg-secondary: #ffffff;
    --bg-card: #ffffff;
    --border: rgba(0,0,0,0.08);
    --text-primary: #09090b;
    --text-secondary: #52525b;
    --text-muted: #a1a1aa;
    --accent: #18181b;
    --accent-hover: #000000;
  }

[ANIMATIONS & INTERACTIONS]
Include at minimum these animation patterns:
1. Fade-in-up on page load:
   @keyframes fadeInUp {
     from { opacity: 0; transform: translateY(20px); }
     to   { opacity: 1; transform: translateY(0); }
   }
   .fade-in { animation: fadeInUp 0.6s ease forwards; }
   Use animation-delay: 0.1s, 0.2s, 0.3s for staggered sections.

2. Hover lift on cards:
   .card { transition: transform 0.2s ease, box-shadow 0.2s ease; }
   .card:hover { transform: translateY(-4px); box-shadow: 0 20px 40px rgba(0,0,0,0.15); }

3. Button press feedback:
   .btn { transition: all 0.15s ease; }
   .btn:hover { transform: translateY(-1px); }
   .btn:active { transform: scale(0.97); }

4. Smooth underline on nav links:
   .nav-link::after { content:''; display:block; height:1px; background:var(--accent); transform:scaleX(0); transition:transform 0.3s ease; }
   .nav-link:hover::after { transform:scaleX(1); }

[LAYOUT]
- Use CSS Grid for page-level layouts
- Use Flexbox for component-level layouts
- ALWAYS include responsive breakpoints:
  @media (max-width: 768px) { ... }
  @media (max-width: 480px) { ... }
- Use max-width: 1200px; margin: 0 auto; padding: 0 24px; for content containers

[VISUAL DETAILS THAT MAKE IT PREMIUM]
- Subtle gradient backgrounds: background: linear-gradient(135deg, #09090b 0%, #0f0f15 100%);
- Glassmorphism cards: background: rgba(255,255,255,0.04); backdrop-filter: blur(12px); border: 1px solid rgba(255,255,255,0.08);
- Grid dot pattern: background-image: radial-gradient(rgba(255,255,255,0.05) 1px, transparent 1px); background-size: 24px 24px;
- Gradient text: background: linear-gradient(135deg, #fff 0%, #a1a1aa 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;
- Box shadows: box-shadow: 0 1px 3px rgba(0,0,0,0.3), 0 8px 24px rgba(0,0,0,0.2);

[JAVASCRIPT]
- All interactivity must be fully wired up and working
- Forms must have real validation with visual feedback (error states, success states)
- Use smooth scroll for anchor links: document.documentElement.style.scrollBehavior = 'smooth';
- Add intersection observers for scroll-triggered animations
- No placeholder alerts — build real in-page feedback

[SELF-CONTAINED]
- Load Google Fonts with <link> in <head>
- Load no external JS frameworks unless explicitly requested
- All CSS must be in <style> tags in index.html or in a separate styles.css file
- The page must render correctly by opening index.html directly in any browser

═══════════════════════════════════════════
STEP 3 — FILE OUTPUT (MANDATORY FORMAT)
═══════════════════════════════════════════
For every file you create or modify, use EXACTLY this format:
--- FILE_START: relative/path/to/file.ext ---
[complete file content — never truncate, never use placeholder comments]
--- FILE_END ---

To delete a file:
--- FILE_DELETE: relative/path/to/file.ext ---

Output your 2-3 line architectural summary FIRST, then all FILE blocks.

FINAL REMINDER: A founder is depending on your output to validate their startup idea tonight.
Your code will be shown to investors. Make it unforgettable.
`;




    // 4. Call processLLMRequest with active context and model routing - Lock to minimalism-flash for now
    const modelId = 'minimalism-flash';
    const explanation = await processLLMRequest(developerSystemPrompt, prompt, filesContext, modelId);

    // 5. Parse LLM response and apply ACTUAL filesystem mutations in real-time
    const fileWriteRegex = /--- FILE_START:\s*([^\s-]+)\s*---([\s\S]*?)--- FILE_END ---/g;
    const fileDeleteRegex = /--- FILE_DELETE:\s*([^\s-]+)\s*---/g;

    const filesWritten: string[] = [];
    const filesDeleted: string[] = [];
    let match;

    // Apply writes
    while ((match = fileWriteRegex.exec(explanation)) !== null) {
      const relativePath = match[1].trim().replace(/\\/g, '/');
      const content = match[2].replace(/^\r?\n|\r?\n$/g, ''); // Trim starting/ending newlines

      try {
        const resolved = safeResolvePath(relativePath);
        const parentDir = path.dirname(resolved);

        if (!fs.existsSync(parentDir)) {
          fs.mkdirSync(parentDir, { recursive: true });
        }

        fs.writeFileSync(resolved, content);
        filesWritten.push(relativePath);
      } catch (err: any) {
        console.error(`Failed to write file ${relativePath}:`, err.message);
      }
    }

    // Apply deletes
    while ((match = fileDeleteRegex.exec(explanation)) !== null) {
      const relativePath = match[1].trim().replace(/\\/g, '/');
      try {
        const resolved = safeResolvePath(relativePath);
        if (fs.existsSync(resolved)) {
          const stat = fs.statSync(resolved);
          if (stat.isDirectory()) {
            fs.rmSync(resolved, { recursive: true, force: true });
          } else {
            fs.unlinkSync(resolved);
          }
          filesDeleted.push(relativePath);
        }
      } catch (err: any) {
        console.error(`Failed to delete file ${relativePath}:`, err.message);
      }
    }

    // Deduct credits
    for (let i = 0; i < creditCost; i++) {
      await queryDb.incrementPromptsUsed(user.id);
    }
    const updatedLedger = await queryDb.getLedger(user.id);

    return res.json({
      success: true,
      explanation, // Returned explanation containing the plan and raw details
      filesWritten,
      filesDeleted,
      creditsRemaining: updatedLedger ? (15 - updatedLedger.daily_prompts_used) : 0
    });

  } catch (error: any) {
    console.error('Autonomous Gen Engine Error:', error);
    return res.status(500).json({ error: error.message || 'Failed in AI generation pipeline.' });
  }
};
